epochs: 10
batch_size: 1
dataset: /mnt/f/wikiarts_5_full_notest/train
style_image: /mnt/y/Latent_Style/Related_Works/baseline_pipeline/results/samst_wikiarts5_wsl_20260610_172206/style_single/Early_Renaissance/
save_model_dir: /mnt/y/Latent_Style/Related_Works/baseline_pipeline/results/samst_wikiarts5_wsl_20260610_172206/checkpoints/Early_Renaissance
image_size: 256
style_size: 512
cuda: 1
seed: 7
content_weight: 100000.0
style_weight: 10000000000.0
ae_weight: 1000.0
lr: 0.001
weight_decay: 0.5
step_size: 25
save_interval: 5
log_interval: 10
checkpoint_interval: 100
checkpoint_model_dir: null
begin_checkpoint: /mnt/y/Latent_Style/Related_Works/baseline_pipeline/results/samst_wikiarts5_wsl_20260610_172206/checkpoints/Early_Renaissance/epoch_5.model
begin_epoch: 5
max_steps: 0
step_model_name_template: step_{step:06d}.model
