ae_weight: 1000.0
batch_size: 1
begin_checkpoint: null
begin_epoch: null
checkpoint_interval: 100
checkpoint_model_dir: null
content_weight: 100000.0
cuda: 1
dataset: ../../train_dataset/content/
epochs: 1
image_size: 256
log_interval: 10
lr: 0.001
save_interval: 1
save_model_dir: G:\GitHub\Latent_Style\run_511\outputs\samst_timing_probe\checkpoints\samst\Hayao
seed: 7
step_size: 25
style_image: ../../train_dataset/style/
style_size: 512
style_weight: 10000000000.0
weight_decay: 0.5
