import gradio as gr
import subprocess
import sys
import os
import signal
import threading
import json
import time
import pandas as pd
from pathlib import Path

# --- Configuration ---
ROOT_DIR = Path(__file__).parent.resolve()
SRC_DIR = ROOT_DIR / "src"
START_SCRIPT = SRC_DIR / "start.py"
DEFAULT_CONFIG_PATH = ROOT_DIR / "config.json"

# --- Global State ---
process = None
log_buffer = []
MAX_LOG_LINES = 2000
lock = threading.Lock()

def get_config_path():
    return DEFAULT_CONFIG_PATH

def load_config_content():
    path = get_config_path()
    if not path.exists():
        return "{}"
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    except Exception as e:
        return f"Error loading config: {e}"

def save_config_content(new_content):
    path = get_config_path()
    try:
        # Validate JSON before saving
        json_obj = json.loads(new_content)
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(json_obj, f, indent=4, ensure_ascii=False)
        return f"Successfully saved to {path}"
    except json.JSONDecodeError as e:
        return f"Invalid JSON: {e}"
    except Exception as e:
        return f"Error saving config: {e}"

def run_training():
    global process, log_buffer
    with lock:
        if process is not None and process.poll() is None:
            return "Training is already running."
        
        log_buffer = ["--- Starting Training ---\n"]
        
        # Prepare command
        # We run from ROOT_DIR so that relative paths in config work as expected
        cmd = [sys.executable, "-u", str(START_SCRIPT)]
        
        try:
            # Start subprocess
            process = subprocess.Popen(
                cmd,
                cwd=str(ROOT_DIR),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                encoding='utf-8',
                errors='replace'
            )
            
            # Start log reader thread
            t = threading.Thread(target=read_process_output, args=(process,), daemon=True)
            t.start()
            
            return "Training started successfully."
        except Exception as e:
            return f"Failed to start training: {e}"

def stop_training():
    global process
    with lock:
        if process is None or process.poll() is not None:
            return "No training process running."
        
        try:
            if sys.platform == "win32":
                process.terminate()
            else:
                os.kill(process.pid, signal.SIGTERM)
            return "Signal sent to stop training."
        except Exception as e:
            return f"Error stopping process: {e}"

def read_process_output(proc):
    global log_buffer
    try:
        for line in iter(proc.stdout.readline, ''):
            with lock:
                log_buffer.append(line)
                if len(log_buffer) > MAX_LOG_LINES:
                    log_buffer.pop(0)
    except Exception as e:
        with lock:
            log_buffer.append(f"\n[Error reading logs: {e}]\n")
    finally:
        proc.stdout.close()

def get_logs():
    with lock:
        return "".join(log_buffer)

def get_status():
    global process
    if process is None:
        return "Not Started"
    code = process.poll()
    if code is None:
        return "Running 🟢"
    return f"Stopped (Code {code}) 🔴"

def parse_metrics():
    """Reads the CSV log file generated by trainer.py"""
    try:
        config_content = load_config_content()
        config = json.loads(config_content)
        
        # Resolve checkpoint dir
        ckpt_dir = Path(config.get('checkpoint', {}).get('save_dir', 'checkpoints'))
        if not ckpt_dir.is_absolute():
            ckpt_dir = ROOT_DIR / ckpt_dir
            
        log_dir = ckpt_dir / 'logs'
        if not log_dir.exists():
            return None
            
        # Find latest CSV
        csv_files = sorted(log_dir.glob("*.csv"), key=os.path.getmtime)
        if not csv_files:
            return None
            
        latest_csv = csv_files[-1]
        df = pd.read_csv(latest_csv)
        return df
    except Exception:
        return None

def get_loss_plot():
    df = parse_metrics()
    if df is None or df.empty:
        return None
    return df

def get_latest_images():
    try:
        config_content = load_config_content()
        config = json.loads(config_content)
        
        ckpt_dir = Path(config.get('checkpoint', {}).get('save_dir', 'checkpoints'))
        if not ckpt_dir.is_absolute():
            ckpt_dir = ROOT_DIR / ckpt_dir
            
        inference_dir = ckpt_dir / 'inference'
        if not inference_dir.exists():
            return []
            
        # Find latest epoch folder
        dirs = [d for d in inference_dir.iterdir() if d.is_dir() and d.name.startswith('epoch_')]
        
        def extract_epoch(d):
            try:
                return int(d.name.split('_')[1])
            except:
                return -1
                
        dirs = sorted(dirs, key=extract_epoch)
        if not dirs:
            return []
            
        latest_dir = dirs[-1]
        images = []
        for ext in ['*.jpg', '*.png', '*.jpeg']:
            images.extend(list(latest_dir.glob(ext)))
            
        return [str(img) for img in images]
    except Exception:
        return []

# --- Gradio Interface ---

with gr.Blocks(title="LGT Cloud Training Manager", theme=gr.themes.Soft()) as app:
    gr.Markdown("# ☁️ LGT Cloud Training Manager")
    
    with gr.Tabs():
        with gr.Tab("🚀 Control & Logs"):
            with gr.Row():
                with gr.Column(scale=1):
                    start_btn = gr.Button("Start Training", variant="primary", size="lg")
                    stop_btn = gr.Button("Stop Training", variant="stop", size="lg")
                    status_display = gr.Textbox(label="Status", value="Not Started", interactive=False)
                    msg_box = gr.Textbox(label="System Message", interactive=False)
                
                with gr.Column(scale=3):
                    logs_box = gr.Code(label="Live Logs", language="text", lines=20)
            
            start_btn.click(run_training, outputs=msg_box)
            stop_btn.click(stop_training, outputs=msg_box)
            
            app.load(get_logs, outputs=logs_box, every=1)
            app.load(get_status, outputs=status_display, every=1)
            
        with gr.Tab("⚙️ Configuration"):
            with gr.Row():
                save_btn = gr.Button("Save Config.json", variant="primary")
                reload_btn = gr.Button("Reload from Disk")
            
            save_status = gr.Textbox(label="Save Status", interactive=False)
            config_editor = gr.Code(label="config.json Editor", language="json", value=load_config_content(), lines=30)
            
            save_btn.click(save_config_content, inputs=config_editor, outputs=save_status)
            reload_btn.click(load_config_content, outputs=config_editor)
            
        with gr.Tab("📈 Metrics & Preview"):
            refresh_viz_btn = gr.Button("Refresh Plots & Images")
            
            with gr.Row():
                loss_chart = gr.LinePlot(
                    x="epoch", y="loss_total",
                    title="Total Loss Curve",
                    tooltip=["epoch", "loss_total", "loss_style_swd", "loss_mse"],
                    width=500, height=300, overlay_point=True
                )
                swd_chart = gr.LinePlot(
                    x="epoch", y="loss_style_swd",
                    title="SWD (Style) Loss",
                    width=500, height=300, overlay_point=True
                )
            
            gr.Markdown("### Latest Inference Results")
            gallery = gr.Gallery(label="Generated Images", columns=4, height="auto")
            
            def refresh_all_viz():
                df = get_loss_plot()
                imgs = get_latest_images()
                if df is None:
                    return None, None, imgs
                return df, df, imgs

            refresh_viz_btn.click(refresh_all_viz, outputs=[loss_chart, swd_chart, gallery])
            app.load(refresh_all_viz, outputs=[loss_chart, swd_chart, gallery], every=30)

if __name__ == "__main__":
    app.queue().launch(server_name="0.0.0.0", server_port=7860, share=False)