#!/bin/bash
# Smart ablation: 159 experiments.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CONFIG_BASE="$ROOT/tools/massive_ablation/configs_smart"
EXP_BASE="$ROOT/exp/620_smart_ablation"

cd "$ROOT"
if [ ! -d "$CONFIG_BASE" ]; then
  echo "Generating smart configs..."
  python "$ROOT/tools/massive_ablation/generate_smart_ablation.py"
fi

TOTAL=159
COUNT=0
FAILED=0
FAILED_LIST=""

run_one() {
  local NAME=$1
  local OUTDIR="$EXP_BASE/$NAME"
  mkdir -p "$OUTDIR"
  cp "$CONFIG_BASE/${NAME}.json" "$OUTDIR/config.json"
  echo "
===================================================================" 
  echo "[$COUNT/$TOTAL] smart: $NAME"
  echo "==================================================================="
  if [ -f "$OUTDIR/full_eval/curve_summary.json" ]; then
    echo "SKIP $NAME (already evaluated)"
    COUNT=$((COUNT+1)); return
  fi
  if python run.py --config "$OUTDIR/config.json" 2>&1 | tee "$OUTDIR/smart.log"; then
    local RC=0
  else
    local RC=$?
    echo "  FAILED $NAME (rc=$RC)"
    FAILED=$((FAILED+1))
    FAILED_LIST="$FAILED_LIST $NAME"
  fi
  COUNT=$((COUNT+1))
}

run_one "abl_swd_0p0_proj_legacy"
run_one "abl_swd_0p0_proj_source_low_target_high"
run_one "abl_swd_0p0_proj_pure_vertical_flow"
run_one "abl_swd_1p0_proj_legacy"
run_one "abl_swd_1p0_proj_source_low_target_high"
run_one "abl_swd_1p0_proj_pure_vertical_flow"
run_one "abl_swd_2p0_proj_legacy"
run_one "abl_swd_2p0_proj_source_low_target_high"
run_one "abl_swd_2p0_proj_pure_vertical_flow"
run_one "abl_swd_5p0_proj_legacy"
run_one "abl_swd_5p0_proj_source_low_target_high"
run_one "abl_swd_5p0_proj_pure_vertical_flow"
run_one "abl_swd_10p0_proj_legacy"
run_one "abl_swd_10p0_proj_source_low_target_high"
run_one "abl_swd_10p0_proj_pure_vertical_flow"
run_one "abl_swd_20p0_proj_legacy"
run_one "abl_swd_20p0_proj_source_low_target_high"
run_one "abl_swd_20p0_proj_pure_vertical_flow"
run_one "abl_swd_50p0_proj_legacy"
run_one "abl_swd_50p0_proj_source_low_target_high"
run_one "abl_swd_50p0_proj_pure_vertical_flow"
run_one "abl_swd_80p0_proj_legacy"
run_one "abl_swd_80p0_proj_source_low_target_high"
run_one "abl_swd_80p0_proj_pure_vertical_flow"
run_one "abl_swd_120p0_proj_legacy"
run_one "abl_swd_120p0_proj_source_low_target_high"
run_one "abl_swd_120p0_proj_pure_vertical_flow"
run_one "abl_swd_200p0_proj_legacy"
run_one "abl_swd_200p0_proj_source_low_target_high"
run_one "abl_swd_200p0_proj_pure_vertical_flow"
run_one "abl_flow_0p0_sig_0p0"
run_one "abl_flow_0p0_sig_0p01"
run_one "abl_flow_0p0_sig_0p02"
run_one "abl_flow_0p0_sig_0p05"
run_one "abl_flow_0p0_sig_0p1"
run_one "abl_flow_0p0_sig_0p2"
run_one "abl_flow_0p1_sig_0p0"
run_one "abl_flow_0p1_sig_0p01"
run_one "abl_flow_0p1_sig_0p02"
run_one "abl_flow_0p1_sig_0p05"
run_one "abl_flow_0p1_sig_0p1"
run_one "abl_flow_0p1_sig_0p2"
run_one "abl_flow_0p2_sig_0p0"
run_one "abl_flow_0p2_sig_0p01"
run_one "abl_flow_0p2_sig_0p02"
run_one "abl_flow_0p2_sig_0p05"
run_one "abl_flow_0p2_sig_0p1"
run_one "abl_flow_0p2_sig_0p2"
run_one "abl_flow_0p5_sig_0p0"
run_one "abl_flow_0p5_sig_0p01"
run_one "abl_flow_0p5_sig_0p02"
run_one "abl_flow_0p5_sig_0p05"
run_one "abl_flow_0p5_sig_0p1"
run_one "abl_flow_0p5_sig_0p2"
run_one "abl_flow_0p8_sig_0p0"
run_one "abl_flow_0p8_sig_0p01"
run_one "abl_flow_0p8_sig_0p02"
run_one "abl_flow_0p8_sig_0p05"
run_one "abl_flow_0p8_sig_0p1"
run_one "abl_flow_0p8_sig_0p2"
run_one "abl_flow_1p0_sig_0p0"
run_one "abl_flow_1p0_sig_0p01"
run_one "abl_flow_1p0_sig_0p02"
run_one "abl_flow_1p0_sig_0p05"
run_one "abl_flow_1p0_sig_0p1"
run_one "abl_flow_1p0_sig_0p2"
run_one "abl_flow_1p5_sig_0p0"
run_one "abl_flow_1p5_sig_0p01"
run_one "abl_flow_1p5_sig_0p02"
run_one "abl_flow_1p5_sig_0p05"
run_one "abl_flow_1p5_sig_0p1"
run_one "abl_flow_1p5_sig_0p2"
run_one "abl_flow_2p0_sig_0p0"
run_one "abl_flow_2p0_sig_0p01"
run_one "abl_flow_2p0_sig_0p02"
run_one "abl_flow_2p0_sig_0p05"
run_one "abl_flow_2p0_sig_0p1"
run_one "abl_flow_2p0_sig_0p2"
run_one "abl_dim_32_blk_2"
run_one "abl_dim_32_blk_4"
run_one "abl_dim_32_blk_6"
run_one "abl_dim_32_blk_8"
run_one "abl_dim_48_blk_2"
run_one "abl_dim_48_blk_4"
run_one "abl_dim_48_blk_6"
run_one "abl_dim_48_blk_8"
run_one "abl_dim_64_blk_2"
run_one "abl_dim_64_blk_4"
run_one "abl_dim_64_blk_6"
run_one "abl_dim_64_blk_8"
run_one "abl_dim_96_blk_2"
run_one "abl_dim_96_blk_4"
run_one "abl_dim_96_blk_6"
run_one "abl_dim_96_blk_8"
run_one "abl_dim_128_blk_2"
run_one "abl_dim_128_blk_4"
run_one "abl_dim_128_blk_6"
run_one "abl_dim_128_blk_8"
run_one "abl_cond_latent_short_0p0_attn_softmax"
run_one "abl_cond_latent_short_0p0_attn_sparsemax"
run_one "abl_cond_latent_short_0p0_attn_gated"
run_one "abl_cond_latent_short_0p2_attn_softmax"
run_one "abl_cond_latent_short_0p2_attn_sparsemax"
run_one "abl_cond_latent_short_0p2_attn_gated"
run_one "abl_cond_latent_short_0p5_attn_softmax"
run_one "abl_cond_latent_short_0p5_attn_sparsemax"
run_one "abl_cond_latent_short_0p5_attn_gated"
run_one "abl_cond_latent_short_1p0_attn_softmax"
run_one "abl_cond_latent_short_1p0_attn_sparsemax"
run_one "abl_cond_latent_short_1p0_attn_gated"
run_one "abl_cond_target_dino_patches_short_0p0_attn_softmax"
run_one "abl_cond_target_dino_patches_short_0p0_attn_sparsemax"
run_one "abl_cond_target_dino_patches_short_0p0_attn_gated"
run_one "abl_cond_target_dino_patches_short_0p2_attn_softmax"
run_one "abl_cond_target_dino_patches_short_0p2_attn_sparsemax"
run_one "abl_cond_target_dino_patches_short_0p2_attn_gated"
run_one "abl_cond_target_dino_patches_short_0p5_attn_softmax"
run_one "abl_cond_target_dino_patches_short_0p5_attn_sparsemax"
run_one "abl_cond_target_dino_patches_short_0p5_attn_gated"
run_one "abl_cond_target_dino_patches_short_1p0_attn_softmax"
run_one "abl_cond_target_dino_patches_short_1p0_attn_sparsemax"
run_one "abl_cond_target_dino_patches_short_1p0_attn_gated"
run_one "abl_ep_velocity"
run_one "abl_ep_endpoint_lowhigh_k_3_hs_0p5"
run_one "abl_ep_endpoint_lowhigh_k_3_hs_1p0"
run_one "abl_ep_endpoint_lowhigh_k_3_hs_1p5"
run_one "abl_ep_endpoint_lowhigh_k_3_hs_2p0"
run_one "abl_ep_endpoint_lowhigh_k_5_hs_0p5"
run_one "abl_ep_endpoint_lowhigh_k_5_hs_1p0"
run_one "abl_ep_endpoint_lowhigh_k_5_hs_1p5"
run_one "abl_ep_endpoint_lowhigh_k_5_hs_2p0"
run_one "abl_ep_endpoint_lowhigh_k_9_hs_0p5"
run_one "abl_ep_endpoint_lowhigh_k_9_hs_1p0"
run_one "abl_ep_endpoint_lowhigh_k_9_hs_1p5"
run_one "abl_ep_endpoint_lowhigh_k_9_hs_2p0"
run_one "abl_ep_endpoint_lowhigh_k_15_hs_0p5"
run_one "abl_ep_endpoint_lowhigh_k_15_hs_1p0"
run_one "abl_ep_endpoint_lowhigh_k_15_hs_1p5"
run_one "abl_ep_endpoint_lowhigh_k_15_hs_2p0"
run_one "abl_ca_0p0_pa_0p0"
run_one "abl_ca_0p0_pa_0p5"
run_one "abl_ca_0p0_pa_0p8"
run_one "abl_ca_0p0_pa_1p0"
run_one "abl_ca_0p1_pa_0p0"
run_one "abl_ca_0p1_pa_0p5"
run_one "abl_ca_0p1_pa_0p8"
run_one "abl_ca_0p1_pa_1p0"
run_one "abl_ca_0p5_pa_0p0"
run_one "abl_ca_0p5_pa_0p5"
run_one "abl_ca_0p5_pa_0p8"
run_one "abl_ca_0p5_pa_1p0"
run_one "abl_ca_1p0_pa_0p0"
run_one "abl_ca_1p0_pa_0p5"
run_one "abl_ca_1p0_pa_0p8"
run_one "abl_ca_1p0_pa_1p0"
run_one "abl_ca_5p0_pa_0p0"
run_one "abl_ca_5p0_pa_0p5"
run_one "abl_ca_5p0_pa_0p8"
run_one "abl_ca_5p0_pa_1p0"

echo "SMART DONE. Total=$TOTAL OK=$((TOTAL-FAILED)) Failed=$FAILED"
