"""Render Table I of the ICME paper from data/main_table.csv.

The CSV is the single source of record for the main comparison; edit values
there (with provenance) and re-run:  python tools/make_main_table.py
Writes table_main.tex next to weave.tex.
"""
import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOARDS = ["D5-512", "P2A-256", "R5-WikiArt"]
METRICS = [("dino_s", True), ("clip_s", True), ("lpips", False), ("dino_c", True)]
REFS = {"Identity", "Target Style"}
DISPLAY = {"Identity": "IDT (identity)", "Target Style": "TGT (target style)"}


def seconds(text):
    m = re.match(r"~?([\d.]+)\s*([smh])", text or "")
    if not m:
        return None
    return float(m.group(1)) * {"s": 1, "m": 60, "h": 3600}[m.group(2)]


def ranks(values, higher_better):
    """Return {method: 1|2} for the best two numeric entries."""
    items = [(m, v) for m, v in values.items() if v is not None]
    items.sort(key=lambda kv: -kv[1] if higher_better else kv[1])
    return {m: i + 1 for i, (m, _) in enumerate(items[:2])}


def mark(text, rank):
    if rank == 1:
        return r"\textbf{%s}" % text
    if rank == 2:
        return r"\underline{%s}" % text
    return text


def main():
    rows = list(csv.DictReader(open(ROOT / "data" / "main_table.csv", encoding="utf-8")))
    methods = list(dict.fromkeys(r["method"] for r in rows))
    val = {(r["method"], r["board"]): r for r in rows}
    cost = {r["method"]: r for r in rows if r["board"] == "D5-512"}

    rank = {}
    for b in BOARDS:
        for key, hib in METRICS:
            vals = {m: float(val[(m, b)][key]) for m in methods if m not in REFS}
            rank[(b, key)] = ranks(vals, hib)
    trained = {m: float(cost[m]["params_trainable_M"]) for m in methods
               if re.fullmatch(r"[\d.]+", cost[m]["params_trainable_M"])
               and float(cost[m]["params_trainable_M"]) > 0}
    rank["params"] = ranks(trained, False)
    train = {m: float(cost[m]["train_min"]) for m in methods
             if re.fullmatch(r"[\d.]+", cost[m]["train_min"])}
    rank["train"] = ranks(train, False)
    infer = {m: seconds(cost[m]["infer_750"]) for m in methods if m not in REFS}
    rank["infer"] = ranks({m: v for m, v in infer.items() if v}, False)

    lines = []
    for m in methods:
        cells = [r"\textbf{WEAVE (ours)}" if m == "WEAVE" else DISPLAY.get(m, m)]
        for b in BOARDS:
            r = val[(m, b)]
            idt, tgt = val[("Identity", b)], val[("Target Style", b)]
            for key, _ in METRICS:
                v = float(r[key])
                txt = "%.3f" % v
                if m not in REFS:
                    # Sandwich marks: style not above IDT, or content beyond TGT.
                    if key in ("dino_s", "clip_s") and v <= float(idt[key]):
                        txt += r"$^{\dagger}$"
                    if key == "lpips" and v >= float(tgt[key]):
                        txt += r"$^{\ddagger}$"
                    if key == "dino_c" and v <= float(tgt[key]):
                        txt += r"$^{\ddagger}$"
                    txt = mark(txt, rank[(b, key)].get(m))
                cells.append(txt)
        c = cost[m]
        p = c["params_trainable_M"]
        if c["params_frozen_M"]:
            p += "$^{+%s}$" % c["params_frozen_M"]
        cells.append(mark(p, rank["params"].get(m)))
        t = c["train_min"].replace("~", r"$\sim$").replace("*", r"$^{\ast}$")
        cells.append(mark(t, rank["train"].get(m)))
        cells.append(mark(c["infer_750"].replace("~", r"$\sim$").replace(" ", r"\,"), rank["infer"].get(m)))
        sep = "\\midrule\n" if m in ("SD-Turbo", "WEAVE") else ""
        lines.append(sep + " & ".join(cells) + r" \\")

    head = r"""\begin{tabular}{@{}l*{12}{c}ccc@{}}
\toprule
& \multicolumn{4}{c}{D5-512} & \multicolumn{4}{c}{P2A-256} & \multicolumn{4}{c}{R5-WikiArt} & Params & Train & Infer \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(lr){10-13}
Method & D-S$\uparrow$ & C-S$\uparrow$ & LP$\downarrow$ & D-C$\uparrow$ & D-S$\uparrow$ & C-S$\uparrow$ & LP$\downarrow$ & D-C$\uparrow$ & D-S$\uparrow$ & C-S$\uparrow$ & LP$\downarrow$ & D-C$\uparrow$ & (M) & (min) & (750) \\
\midrule
"""
    out = "% Generated by tools/make_main_table.py from data/main_table.csv; do not edit by hand.\n"
    out += head + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n"
    (ROOT / "table_main.tex").write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
