#!/bin/bash
# 620 Ablation Sweep: 1-epoch experiments, run sequentially
# Generated: 217 experiments
set -euo pipefail

SRC_DIR="/mnt/i/Github/Latent_Style/SchrodingerBridge/src"
EXP_BASE="/mnt/i/Github/Latent_Style/exp/620_spatial_bridge"
CONFIG_BASE="/mnt/i/Github/Latent_Style/SchrodingerBridge/tools/ablation256/configs"

cd "$SRC_DIR"
export PYTHONPATH="$SRC_DIR"

TOTAL=217
COUNT=0
FAILED=0
FAILED_LIST=""

run_one() {
  local NAME=$1
  local CFG="$CONFIG_BASE/${NAME}.json"
  local OUTDIR="$EXP_BASE/$NAME"
  mkdir -p "$OUTDIR"
  # Copy config into experiment dir
  cp "$CFG" "$OUTDIR/config.json"
  echo "[$COUNT/$TOTAL] Starting $NAME ..."
  python3 run.py --config "$OUTDIR/config.json" > "$OUTDIR/train.log" 2>&1
  local RC=$?
  if [ $RC -ne 0 ]; then
    echo "  FAILED (rc=$RC)"
    FAILED=$((FAILED+1))
    FAILED_LIST="$FAILED_LIST $NAME"
  else
    echo "  OK"
  fi
  COUNT=$((COUNT+1))
}

run_one "A_abl_attn_mode_softmax_gate_init_0p05"
run_one "A_abl_attn_mode_softmax_gate_init_0p1"
run_one "A_abl_attn_mode_softmax_gate_init_0p3"
run_one "A_abl_attn_mode_softmax_gate_init_0p5"
run_one "A_abl_attn_mode_gated_gate_init_0p05"
run_one "A_abl_attn_mode_gated_gate_init_0p1"
run_one "A_abl_attn_mode_gated_gate_init_0p3"
run_one "A_abl_attn_mode_gated_gate_init_0p5"
run_one "A_abl_attn_mode_gated_raw_gate_init_0p05"
run_one "A_abl_attn_mode_gated_raw_gate_init_0p1"
run_one "A_abl_attn_mode_gated_raw_gate_init_0p3"
run_one "A_abl_attn_mode_gated_raw_gate_init_0p5"
run_one "A_abl_attn_mode_relu2_gate_init_0p05"
run_one "A_abl_attn_mode_relu2_gate_init_0p1"
run_one "A_abl_attn_mode_relu2_gate_init_0p3"
run_one "A_abl_attn_mode_relu2_gate_init_0p5"
run_one "A_abl_attn_mode_style_select_gate_init_0p05"
run_one "A_abl_attn_mode_style_select_gate_init_0p1"
run_one "A_abl_attn_mode_style_select_gate_init_0p3"
run_one "A_abl_attn_mode_style_select_gate_init_0p5"
run_one "A_abl_attn_mode_sparsemax_gate_init_0p05"
run_one "A_abl_attn_mode_sparsemax_gate_init_0p1"
run_one "A_abl_attn_mode_sparsemax_gate_init_0p3"
run_one "A_abl_attn_mode_sparsemax_gate_init_0p5"
echo "=== Progress: 24/217 ==="
run_one "B_abl_ep_mode_velocity_ep_film_T_ep_hd_64"
run_one "B_abl_ep_mode_velocity_ep_film_T_ep_hd_128"
run_one "B_abl_ep_mode_velocity_ep_film_T_ep_hd_256"
run_one "B_abl_ep_mode_velocity_ep_film_T_ep_hd_512"
run_one "B_abl_ep_mode_velocity_ep_film_F_ep_hd_64"
run_one "B_abl_ep_mode_velocity_ep_film_F_ep_hd_128"
run_one "B_abl_ep_mode_velocity_ep_film_F_ep_hd_256"
run_one "B_abl_ep_mode_velocity_ep_film_F_ep_hd_512"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_64_ep_film_init_0p0"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_64_ep_film_init_0p01"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_64_ep_film_init_0p02"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_64_ep_film_init_0p05"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_128_ep_film_init_0p0"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_128_ep_film_init_0p01"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_128_ep_film_init_0p02"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_128_ep_film_init_0p05"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_256_ep_film_init_0p0"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_256_ep_film_init_0p01"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_256_ep_film_init_0p02"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_256_ep_film_init_0p05"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_512_ep_film_init_0p0"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_512_ep_film_init_0p01"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_512_ep_film_init_0p02"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_T_ep_hd_512_ep_film_init_0p05"
echo "=== Progress: 48/217 ==="
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_F_ep_hd_64"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_F_ep_hd_128"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_F_ep_hd_256"
run_one "B_abl_ep_mode_endpoint_lowhigh_ep_film_F_ep_hd_512"
run_one "C_abl_block_film_T_block_shortcut_0p5"
run_one "C_abl_block_film_T_block_shortcut_1p0"
run_one "C_abl_block_film_F_block_shortcut_0p5"
run_one "C_abl_block_film_F_block_shortcut_1p0"
run_one "D_abl_swd_w_0p0_edge_w_0p0_swd_sigma_0p0"
run_one "D_abl_swd_w_0p0_edge_w_0p0_swd_sigma_0p02"
run_one "D_abl_swd_w_0p0_edge_w_0p0_swd_sigma_0p05"
run_one "D_abl_swd_w_0p0_edge_w_0p1_swd_sigma_0p0"
run_one "D_abl_swd_w_0p0_edge_w_0p1_swd_sigma_0p02"
run_one "D_abl_swd_w_0p0_edge_w_0p1_swd_sigma_0p05"
run_one "D_abl_swd_w_0p0_edge_w_0p5_swd_sigma_0p0"
run_one "D_abl_swd_w_0p0_edge_w_0p5_swd_sigma_0p02"
run_one "D_abl_swd_w_0p0_edge_w_0p5_swd_sigma_0p05"
run_one "D_abl_swd_w_4p0_edge_w_0p0_swd_sigma_0p0"
run_one "D_abl_swd_w_4p0_edge_w_0p0_swd_sigma_0p02"
run_one "D_abl_swd_w_4p0_edge_w_0p0_swd_sigma_0p05"
run_one "D_abl_swd_w_4p0_edge_w_0p1_swd_sigma_0p0"
run_one "D_abl_swd_w_4p0_edge_w_0p1_swd_sigma_0p02"
run_one "D_abl_swd_w_4p0_edge_w_0p1_swd_sigma_0p05"
run_one "D_abl_swd_w_4p0_edge_w_0p5_swd_sigma_0p0"
echo "=== Progress: 72/217 ==="
run_one "D_abl_swd_w_4p0_edge_w_0p5_swd_sigma_0p02"
run_one "D_abl_swd_w_4p0_edge_w_0p5_swd_sigma_0p05"
run_one "D_abl_swd_w_8p0_edge_w_0p0_swd_sigma_0p0"
run_one "D_abl_swd_w_8p0_edge_w_0p0_swd_sigma_0p02"
run_one "D_abl_swd_w_8p0_edge_w_0p0_swd_sigma_0p05"
run_one "D_abl_swd_w_8p0_edge_w_0p1_swd_sigma_0p0"
run_one "D_abl_swd_w_8p0_edge_w_0p1_swd_sigma_0p02"
run_one "D_abl_swd_w_8p0_edge_w_0p1_swd_sigma_0p05"
run_one "D_abl_swd_w_8p0_edge_w_0p5_swd_sigma_0p0"
run_one "D_abl_swd_w_8p0_edge_w_0p5_swd_sigma_0p02"
run_one "D_abl_swd_w_8p0_edge_w_0p5_swd_sigma_0p05"
run_one "D_abl_swd_w_16p0_edge_w_0p0_swd_sigma_0p0"
run_one "D_abl_swd_w_16p0_edge_w_0p0_swd_sigma_0p02"
run_one "D_abl_swd_w_16p0_edge_w_0p0_swd_sigma_0p05"
run_one "D_abl_swd_w_16p0_edge_w_0p1_swd_sigma_0p0"
run_one "D_abl_swd_w_16p0_edge_w_0p1_swd_sigma_0p02"
run_one "D_abl_swd_w_16p0_edge_w_0p1_swd_sigma_0p05"
run_one "D_abl_swd_w_16p0_edge_w_0p5_swd_sigma_0p0"
run_one "D_abl_swd_w_16p0_edge_w_0p5_swd_sigma_0p02"
run_one "D_abl_swd_w_16p0_edge_w_0p5_swd_sigma_0p05"
run_one "E_abl_proj_mode_source_low_target_high_low_mode_all_low_anchor_0p5"
run_one "E_abl_proj_mode_source_low_target_high_low_mode_all_low_anchor_1p0"
run_one "E_abl_proj_mode_source_low_target_high_low_mode_channel_mean_low_anchor_0p5"
run_one "E_abl_proj_mode_source_low_target_high_low_mode_channel_mean_low_anchor_1p0"
echo "=== Progress: 96/217 ==="
run_one "E_abl_proj_mode_source_low_target_high_low_mode_target_linear_low_anchor_0p5"
run_one "E_abl_proj_mode_source_low_target_high_low_mode_target_linear_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_all_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_all_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_channel_mean_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_channel_mean_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_target_linear_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_low_mode_target_linear_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_all_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_all_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_channel_mean_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_channel_mean_low_anchor_1p0"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_target_linear_low_anchor_0p5"
run_one "E_abl_proj_mode_pure_vertical_flow_wavelet_low_mode_target_linear_low_anchor_1p0"
run_one "F_abl_dino_adapter_T_dino_moe_T_query_src_concat"
run_one "F_abl_dino_adapter_T_dino_moe_T_query_src_sa_out_only"
run_one "F_abl_dino_adapter_T_dino_moe_F_query_src_concat"
run_one "F_abl_dino_adapter_T_dino_moe_F_query_src_sa_out_only"
run_one "F_abl_dino_adapter_F_dino_moe_T_query_src_concat"
run_one "F_abl_dino_adapter_F_dino_moe_T_query_src_sa_out_only"
run_one "F_abl_dino_adapter_F_dino_moe_F_query_src_concat"
run_one "F_abl_dino_adapter_F_dino_moe_F_query_src_sa_out_only"
run_one "G_abl_n_blocks_2_base_dim_64"
run_one "G_abl_n_blocks_2_base_dim_128"
echo "=== Progress: 120/217 ==="
run_one "G_abl_n_blocks_4_base_dim_64"
run_one "G_abl_n_blocks_4_base_dim_128"
run_one "G_abl_n_blocks_6_base_dim_64"
run_one "G_abl_n_blocks_6_base_dim_128"
run_one "H_abl_lr_0p0001_batch_24_vlen_0p04"
run_one "H_abl_lr_0p0001_batch_24_vlen_0p2"
run_one "H_abl_lr_0p0001_batch_24_vlen_1p0"
run_one "H_abl_lr_0p0001_batch_48_vlen_0p04"
run_one "H_abl_lr_0p0001_batch_48_vlen_0p2"
run_one "H_abl_lr_0p0001_batch_48_vlen_1p0"
run_one "H_abl_lr_0p0002_batch_24_vlen_0p04"
run_one "H_abl_lr_0p0002_batch_24_vlen_0p2"
run_one "H_abl_lr_0p0002_batch_24_vlen_1p0"
run_one "H_abl_lr_0p0002_batch_48_vlen_0p04"
run_one "H_abl_lr_0p0002_batch_48_vlen_0p2"
run_one "H_abl_lr_0p0002_batch_48_vlen_1p0"
run_one "H_abl_lr_0p0005_batch_24_vlen_0p04"
run_one "H_abl_lr_0p0005_batch_24_vlen_0p2"
run_one "H_abl_lr_0p0005_batch_24_vlen_1p0"
run_one "H_abl_lr_0p0005_batch_48_vlen_0p04"
run_one "H_abl_lr_0p0005_batch_48_vlen_0p2"
run_one "H_abl_lr_0p0005_batch_48_vlen_1p0"
run_one "I_abl_entropy_reg_0p0_energy_band_0p0_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p0_energy_band_0p0_anchor_noise_0p01"
echo "=== Progress: 144/217 ==="
run_one "I_abl_entropy_reg_0p0_energy_band_0p1_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p0_energy_band_0p1_anchor_noise_0p01"
run_one "I_abl_entropy_reg_0p01_energy_band_0p0_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p01_energy_band_0p0_anchor_noise_0p01"
run_one "I_abl_entropy_reg_0p01_energy_band_0p1_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p01_energy_band_0p1_anchor_noise_0p01"
run_one "I_abl_entropy_reg_0p1_energy_band_0p0_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p1_energy_band_0p0_anchor_noise_0p01"
run_one "I_abl_entropy_reg_0p1_energy_band_0p1_anchor_noise_0p0"
run_one "I_abl_entropy_reg_0p1_energy_band_0p1_anchor_noise_0p01"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p0_ep_lp_3"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p0_ep_lp_5"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p0_ep_lp_7"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p05_ep_lp_3"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p05_ep_lp_5"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p05_ep_lp_7"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p1_ep_lp_3"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p1_ep_lp_5"
run_one "J_abl_ep_high_0p5_ep_vfloor_0p1_ep_lp_7"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p0_ep_lp_3"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p0_ep_lp_5"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p0_ep_lp_7"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p05_ep_lp_3"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p05_ep_lp_5"
echo "=== Progress: 168/217 ==="
run_one "J_abl_ep_high_1p0_ep_vfloor_0p05_ep_lp_7"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p1_ep_lp_3"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p1_ep_lp_5"
run_one "J_abl_ep_high_1p0_ep_vfloor_0p1_ep_lp_7"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p0_ep_lp_3"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p0_ep_lp_5"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p0_ep_lp_7"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p05_ep_lp_3"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p05_ep_lp_5"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p05_ep_lp_7"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p1_ep_lp_3"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p1_ep_lp_5"
run_one "J_abl_ep_high_2p0_ep_vfloor_0p1_ep_lp_7"
run_one "K_abl_attn_temp_0p5_attn_topk_0_skip_coarse_T"
run_one "K_abl_attn_temp_0p5_attn_topk_0_skip_coarse_F"
run_one "K_abl_attn_temp_0p5_attn_topk_4_skip_coarse_T"
run_one "K_abl_attn_temp_0p5_attn_topk_4_skip_coarse_F"
run_one "K_abl_attn_temp_0p5_attn_topk_16_skip_coarse_T"
run_one "K_abl_attn_temp_0p5_attn_topk_16_skip_coarse_F"
run_one "K_abl_attn_temp_1p0_attn_topk_0_skip_coarse_T"
run_one "K_abl_attn_temp_1p0_attn_topk_0_skip_coarse_F"
run_one "K_abl_attn_temp_1p0_attn_topk_4_skip_coarse_T"
run_one "K_abl_attn_temp_1p0_attn_topk_4_skip_coarse_F"
run_one "K_abl_attn_temp_1p0_attn_topk_16_skip_coarse_T"
echo "=== Progress: 192/217 ==="
run_one "K_abl_attn_temp_1p0_attn_topk_16_skip_coarse_F"
run_one "K_abl_attn_temp_2p0_attn_topk_0_skip_coarse_T"
run_one "K_abl_attn_temp_2p0_attn_topk_0_skip_coarse_F"
run_one "K_abl_attn_temp_2p0_attn_topk_4_skip_coarse_T"
run_one "K_abl_attn_temp_2p0_attn_topk_4_skip_coarse_F"
run_one "K_abl_attn_temp_2p0_attn_topk_16_skip_coarse_T"
run_one "K_abl_attn_temp_2p0_attn_topk_16_skip_coarse_F"
run_one "L_abl_pair_topk_1_pair_cross_T"
run_one "L_abl_pair_topk_1_pair_cross_F"
run_one "L_abl_pair_topk_4_pair_cross_T"
run_one "L_abl_pair_topk_4_pair_cross_F"
run_one "L_abl_pair_topk_8_pair_cross_T"
run_one "L_abl_pair_topk_8_pair_cross_F"
run_one "M_abl_b_sigma_0p0_t_power_1p0_t_min_0p0"
run_one "M_abl_b_sigma_0p0_t_power_1p0_t_min_0p1"
run_one "M_abl_b_sigma_0p0_t_power_2p0_t_min_0p0"
run_one "M_abl_b_sigma_0p0_t_power_2p0_t_min_0p1"
run_one "M_abl_b_sigma_0p02_t_power_1p0_t_min_0p0"
run_one "M_abl_b_sigma_0p02_t_power_1p0_t_min_0p1"
run_one "M_abl_b_sigma_0p02_t_power_2p0_t_min_0p0"
run_one "M_abl_b_sigma_0p02_t_power_2p0_t_min_0p1"
run_one "M_abl_b_sigma_0p05_t_power_1p0_t_min_0p0"
run_one "M_abl_b_sigma_0p05_t_power_1p0_t_min_0p1"
run_one "M_abl_b_sigma_0p05_t_power_2p0_t_min_0p0"
echo "=== Progress: 216/217 ==="
run_one "M_abl_b_sigma_0p05_t_power_2p0_t_min_0p1"

echo ""
echo "=========================================="
echo "ALL DONE. Total=$TOTAL OK=$((TOTAL-FAILED)) Failed=$FAILED"
if [ $FAILED -gt 0 ]; then
  echo "Failed experiments:$FAILED_LIST"
fi
