#!/usr/bin/env bash
# Remote cleanup script: delete smoke/probe/invalid directories with logging
# Generated by Deli_AutoResearch cleanup task M1
# Date: 2026-07-02
set -uo pipefail

LOG=/mnt/i/Github/Latent_Style/_cleanup_m1.log
RESULTS=/mnt/i/Github/Latent_Style/_cleanup_m1.results
echo "=== M1 Cleanup Start: $(date -Iseconds) ===" > "$LOG"
echo "" > "$RESULTS"

deleted_count=0
freed_bytes=0

delete_dir() {
    local dir="$1"
    local reason="$2"
    if [ ! -d "$dir" ]; then
        echo "SKIP (not exists): $dir" >> "$LOG"
        return 0
    fi
    local size_before=$(du -sb "$dir" 2>/dev/null | awk '{print $1}')
    local size_human=$(du -sh "$dir" 2>/dev/null | awk '{print $1}')
    echo "DELETE: $dir | size=$size_human | reason=$reason" >> "$LOG"
    rm -rf "$dir"
    if [ ! -d "$dir" ]; then
        echo "OK: $dir | $size_human | $reason" >> "$RESULTS"
        deleted_count=$((deleted_count + 1))
        freed_bytes=$((freed_bytes + ${size_before:-0}))
    else
        echo "FAIL: $dir" >> "$RESULTS"
    fi
}

# ==================== Group 1: img2img_turbo smoke (40 dirs) ====================
echo "--- Group 1: img2img_turbo smoke ---" >> "$LOG"
RUNS=/mnt/i/Github/Latent_Style/Related_Works/runs

# 9 large smoke (75M each)
for ts in 20260606_052126 20260606_052546 20260606_055754 20260606_060315 20260606_060823 \
          20260606_061146 20260606_061608 20260606_062547 20260606_190514 20260606_192636; do
    delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_$ts" "img2img_turbo_smoke_75M"
done

# 3 medium smoke (460M each, with _datasets_ suffix - 19 total)
for ts in 20260606_050156 20260606_050239 20260606_050448 20260606_050640 20260606_051058 \
          20260606_051309 20260606_051439 20260606_052126 20260606_052546 20260606_055754 \
          20260606_060315 20260606_060823 20260606_061146 20260606_061608 20260606_062547 \
          20260606_185423 20260606_190514 20260606_192636; do
    delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_datasets_$ts" "img2img_turbo_smoke_460M"
done

# small/medium primary smoke (24K-44K, plus the 1014M and 192M and 54M ones)
delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_20260606_202920" "img2img_turbo_smoke_1014M"
delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_20260606_201322" "img2img_turbo_smoke_192M"
delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_datasets_20260606_201322" "img2img_turbo_smoke_datasets_54M"
delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_datasets_20260606_202920" "img2img_turbo_smoke_datasets_54M"
delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_20260606_185423" "img2img_turbo_smoke_44K"

# tiny 24K initial probes
for ts in 20260606_050156 20260606_050239 20260606_050448 20260606_050640 20260606_051058 \
          20260606_051309 20260606_051439; do
    delete_dir "$RUNS/img2img_turbo_distinct5_remote_smoke_$ts" "img2img_turbo_smoke_24K"
done

# Other baseline runs that were just smoke
delete_dir "$RUNS/cyclegan_5x5_smoke" "cyclegan_smoke"
delete_dir "$RUNS/lbm_train_smoke_run" "lbm_smoke"
delete_dir "$RUNS/lbm_train_wds_smoke_photo_to_monet" "lbm_smoke_empty"

# ==================== Group 2: SaMam/SaMST failed probes (28 dirs, all <200K) ====================
echo "--- Group 2: SaMam/SaMST failed probes ---" >> "$LOG"
RESULTS_DIR=/mnt/i/Github/Latent_Style/Related_Works/baseline_pipeline/results

delete_dir "$RESULTS_DIR/samam_latent_distinct5_512_samecost_20260606_162544" "samam_probe_24K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_512_samecost_20260606_133519" "samam_probe_56K"
delete_dir "$RESULTS_DIR/samst_latent_distinct5_512_samecost_20260606_035344" "samst_probe_8K"
delete_dir "$RESULTS_DIR/samst_latent_distinct5_512_samecost_20260606_035136" "samst_probe_12K"
delete_dir "$RESULTS_DIR/samst_latent_distinct5_512_samecost_20260606_040419" "samst_probe_4K"
delete_dir "$RESULTS_DIR/samst_latent_distinct5_512_samecost_20260606_035731" "samst_probe_4K"
delete_dir "$RESULTS_DIR/samst_latent_distinct5_512_samecost_20260606_035540" "samst_probe_8K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_512_samecost_20260606_034632" "samam_probe_20K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_512_samecost_20260606_034359" "samam_probe_52K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_512_samecost_20260606_034059" "samam_probe_28K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_samecost_probe3" "samam_probe_16K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_samecost_probe2" "samam_probe_8K"
delete_dir "$RESULTS_DIR/samam_latent_distinct5_samecost_probe1" "samam_probe_8K"
delete_dir "$RESULTS_DIR/samam_latent_legacy256_probe3" "samam_probe_24K"
delete_dir "$RESULTS_DIR/samam_latent_legacy256_probe2" "samam_probe_48K"
delete_dir "$RESULTS_DIR/samam_latent_legacy256_probe" "samam_probe_20K"
delete_dir "$RESULTS_DIR/samam_latent_legacy256_remote" "samam_probe_28K"
delete_dir "$RESULTS_DIR/samst_latent_legacy256_probe3" "samst_probe_120K"
delete_dir "$RESULTS_DIR/samst_latent_legacy256_probe1" "samst_probe_116K"
delete_dir "$RESULTS_DIR/samst_latent_legacy256_probe2" "samst_probe_120K"
delete_dir "$RESULTS_DIR/samst_distinct5_512_prepared" "samst_probe_8K"
delete_dir "$RESULTS_DIR/samam_distinct5_512_mamba_b6_seg250_remote_wsl_20260601_2130" "samam_probe_16K"
delete_dir "$RESULTS_DIR/samam_distinct5_512_mamba_b8_20k_remote_wsl_20260601_1850" "samam_probe_16K"
delete_dir "$RESULTS_DIR/samam_distinct5_512_mamba_b1_20k_remote_wsl_20260601_1830b" "samam_probe_12K"
delete_dir "$RESULTS_DIR/samam_distinct5_512_mamba_b1_20k_remote_wsl_20260601_1830" "samam_probe_8K"
delete_dir "$RESULTS_DIR/samam_256_faithful_p8_remote_debug_foreground" "samam_debug_104K"
delete_dir "$RESULTS_DIR/samam_256_faithful_p8_remote_debug_idckpt" "samam_debug_108K"
delete_dir "$RESULTS_DIR/samam_256_faithful_p8_remote_debug" "samam_debug_12K"

# ==================== Group 3: aaai2027 invalid/empty (14 dirs, all <1M) ====================
echo "--- Group 3: aaai2027 invalid/empty ---" >> "$LOG"
EXP=/mnt/i/Github/Latent_Style/exp

# aaai2027 invalid_no_parent duplicates (explicitly named _invalid_)
for d in \
    aaai2027_phase2_i2sb_orthogonal_lowanchor050_k070_e3_sigma0p02_b8a2_vlen010_invalid_no_parent_20260616_114924 \
    aaai2027_phase2_i2sb_orthogonal_lowanchor050_k070_e3_sigma0p02_b8a2_vlen010_invalid_no_parent_20260616_115546; do
    delete_dir "$EXP/$d" "aaai2027_invalid_no_parent"
done

# aaai2027 fiber_project evals (all 80-108K, no ckpt, no images - failed evals)
for d in \
    aaai2027_eval_fiber_project_slerpe2_sigma0p0 \
    aaai2027_eval_fiber_project_slerpe2_sigma0p5 \
    aaai2027_eval_fiber_project_lowanchor050e9_sigma0p0 \
    aaai2027_eval_fiber_project_lowanchor050e9_sigma1p0 \
    aaai2027_eval_fiber_project_lowanchor050e9_sigma1p5 \
    aaai2027_eval_fiber_project_lowanchor050e9_sigma0p5; do
    delete_dir "$EXP/$d" "aaai2027_eval_failed"
done

# aaai2027 phase2 empty/failed (668K-984K, 0 ckpt)
for d in \
    aaai2027_phase2_i2sb_orthogonal_lowanchor050_k070_e3_sigma0p02_b8a2_vlen010 \
    aaai2027_phase2_vel_tok32_safe_semantic_topogate_k070_kin070_seed42_b12a1 \
    aaai2027_phase2_vel_tok32_safe_semantic_topogate_k085_appalign_seed42_b16a1 \
    aaai2027_phase2_vel_tok32_safe_semantic_topogate_k085_seed42_b20a1 \
    aaai2027_phase2_i2sb_pattn_topo_anchor_sigma0p10_warm_vel2_seed42_b24a1 \
    aaai2027_phase2_i2sb_pattn_topo_anchor_sigma0p10_warm_vel2_seed42_b26a1 \
    aaai2027_phase2_i2sb_topo_anchor_sigma0p25_seed42_b22a1; do
    # Note: there are TWO aaai2027_phase2_i2sb_orthogonal_lowanchor050... dirs (one valid 940K, one 940K empty)
    # We delete ONLY if 0 ckpts found
    ckpt_count=$(find "$EXP/$d" -name "*.ckpt" -o -name "*.pt" -o -name "*.pth" 2>/dev/null | wc -l)
    if [ "$ckpt_count" -eq 0 ]; then
        delete_dir "$EXP/$d" "aaai2027_empty_0ckpt"
    else
        echo "KEEP (has $ckpt_count ckpts): $d" >> "$LOG"
    fi
done

# ==================== Summary ====================
echo "" >> "$LOG"
echo "=== M1 Cleanup End: $(date -Iseconds) ===" >> "$LOG"
echo "Deleted: $deleted_count directories" >> "$LOG"
echo "Freed: $freed_bytes bytes (approx $(echo "scale=2; $freed_bytes/1073741824" | bc) GiB)" >> "$LOG"
echo ""
echo "=== Summary ==="
cat "$RESULTS" | wc -l
echo "deleted directories (see $RESULTS)"
echo "Freed: $freed_bytes bytes (approx $(echo "scale=2; $freed_bytes/1073741824" | bc) GiB)"
