#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-python}"
VRAM_PROFILE="${VRAM_PROFILE:-7g}"
RUN_ROOT="${RUN_ROOT:-${REPO_ROOT}/Related_Works/runs/server_new_baselines/${VRAM_PROFILE}}"

case "${VRAM_PROFILE}" in
  4g)
    BATCH_SIZE="${BATCH_SIZE:-1}"
    LOAD_SIZE="${LOAD_SIZE:-128}"
    CROP_SIZE="${CROP_SIZE:-128}"
    IMAGES_PER_STYLE="${IMAGES_PER_STYLE:-16}"
    AESFA_ITERS="${AESFA_ITERS:-200}"
    STYTR2_ITERS="${STYTR2_ITERS:-200}"
    AESPA_ITERS="${AESPA_ITERS:-200}"
    NUM_WORKERS="${NUM_WORKERS:-0}"
    ;;
  7g)
    BATCH_SIZE="${BATCH_SIZE:-1}"
    LOAD_SIZE="${LOAD_SIZE:-192}"
    CROP_SIZE="${CROP_SIZE:-192}"
    IMAGES_PER_STYLE="${IMAGES_PER_STYLE:-32}"
    AESFA_ITERS="${AESFA_ITERS:-500}"
    STYTR2_ITERS="${STYTR2_ITERS:-500}"
    AESPA_ITERS="${AESPA_ITERS:-500}"
    NUM_WORKERS="${NUM_WORKERS:-2}"
    ;;
  11g)
    BATCH_SIZE="${BATCH_SIZE:-2}"
    LOAD_SIZE="${LOAD_SIZE:-256}"
    CROP_SIZE="${CROP_SIZE:-256}"
    IMAGES_PER_STYLE="${IMAGES_PER_STYLE:-64}"
    AESFA_ITERS="${AESFA_ITERS:-1000}"
    STYTR2_ITERS="${STYTR2_ITERS:-1000}"
    AESPA_ITERS="${AESPA_ITERS:-1000}"
    NUM_WORKERS="${NUM_WORKERS:-4}"
    ;;
  *)
    echo "Unknown VRAM_PROFILE='${VRAM_PROFILE}'. Use 4g, 7g, or 11g." >&2
    exit 2
    ;;
esac

mkdir -p "${RUN_ROOT}/logs"

echo "[profile] VRAM_PROFILE=${VRAM_PROFILE}"
echo "[profile] RUN_ROOT=${RUN_ROOT}"
echo "[profile] BATCH_SIZE=${BATCH_SIZE} LOAD_SIZE=${LOAD_SIZE} CROP_SIZE=${CROP_SIZE}"
echo "[profile] IMAGES_PER_STYLE=${IMAGES_PER_STYLE} NUM_WORKERS=${NUM_WORKERS}"
echo "[profile] AESFA_ITERS=${AESFA_ITERS} STYTR2_ITERS=${STYTR2_ITERS} AESPA_ITERS=${AESPA_ITERS}"

cd "${REPO_ROOT}"
